return {
  "shellRaining/hlchunk.nvim",
  event = { "UIEnter" },
  config = function()
    require("hlchunk").setup({
      blank = { enable = false },
      indent = { enable = false },
      chunk = {
        enable = false,
        chars = {
          horizontal_line = "─",
          vertical_line = "│",
          left_top = "┌",
          left_bottom = "└",
          right_arrow = "",
        },
        exclude_filetypes = {
          aerial = true,
          dashboard = true,
          help = true,
          lspinfo = true,
          lspsagafinder = true,
          packer = true,
          checkhealth = true,
          man = true,
          mason = true,
          NvimTree = true,
          ["neo-tree"] = true,
          plugin = true,
          lazy = true,
          TelescopePrompt = true,
          [""] = true, -- because TelescopePrompt will set a empty ft, so add this.
          alpha = true,
          toggleterm = true,
          sagafinder = true,
          sagaoutline = true,
          better_term = true,
          fugitiveblame = true,
        },
        style = "#65BCFF",
      },
      line_num = {
        style = "#65BCFF",
        exclude_filetypes = {
          aerial = true,
          dashboard = true,
          help = true,
          lspinfo = true,
          lspsagafinder = true,
          packer = true,
          checkhealth = true,
          man = true,
          mason = true,
          NvimTree = true,
          ["neo-tree"] = true,
          plugin = true,
          lazy = true,
          TelescopePrompt = true,
          [""] = true, -- because TelescopePrompt will set a empty ft, so add this.
          alpha = true,
          toggleterm = true,
          sagafinder = true,
          sagaoutline = true,
          better_term = true,
          fugitiveblame = true,
        },
      },
    })
  end,
}
