return {
  "LazyVim/LazyVim",
  opts = {
    colorscheme = "catppuccin",
    icons = {
      dap = {
        Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
        Breakpoint = " ",
        BreakpointCondition = " ",
        BreakpointRejected = { " ", "DiagnosticError" },
        LogPoint = ".>",
      },
      diagnostics = {
        Error = " ",
        Warn = " ",
        Hint = " ",
        Info = " ",
      },
      git = {
        added = " ",
        modified = " ",
        remoed = " ",
      },
      kinds = {
        Array = " ",
        Boolean = " ",
        Color = " ",
        Copilot = " ",
        Field = " ",
        Key = " ",
        Namespace = " ",
        Null = " ",
        Number = " ",
        Object = " ",
        Package = " ",
        Snippet = " ",
        String = " ",
        Text = "󰧭 ",
        Unit = "󰑭 ",
        Method = "󰆧 ",
        Function = "󰡱 ",
        Constructor = " ",
        Variable = "󰂡 ",
        Class = "󰠱 ",
        Interface = " ",
        Module = "󰏗 ",
        Property = "󰜢 ",
        Value = "󰎠 ",
        Enum = " ",
        Keyword = "󰌋 ",
        File = "󰧮 ",
        Reference = " ",
        Folder = " ",
        EnumMember = " ",
        Constant = "󰏿 ",
        Struct = " ",
        Eent = " ",
        Operator = "󰆕 ",
        TypeParameter = "󰅲 ",
      },
    },
  },
}
